CREATE OR REPLACE VIEW Project_View AS
SELECT PROJ_ID, PROJECT.CUST_ID, PROJECT.MANAGER_ID, PROJECT.PRJ_DESCRIPTION, 
PROJECT.PRJ_CONTRACT_DATE, PROJECT.EST_PRJ_START_DATE, PROJECT.EST_PRJ_END_DATE, 
PROJECT.EST_PROJECT_BUDGET, CUSTOMER.CUST_FNAME, CUSTOMER.CUST_LNAME
FROM PROJECT
JOIN CUSTOMER ON PROJECT.CUST_ID=CUSTOMER.CUST_ID

ORDER BY LENGTH (PROJ_ID), PROJ_ID ASC;
SELECT * FROM Project_View;