CREATE PROCEDURE SHOW_DATA
AS
BEGIN
    SELECT INTO * FROM REGION;
    SELECT INTO * FROM SKILL_COLLECTION;
    SELECT INTO * FROM EMPLOYEE;
    SELECT INTO * FROM EMPLOYEE_SKILL;
    SELECT INTO * FROM CUSTOMER;
    SELECT INTO * FROM MANAGER;
    SELECT INTO * FROM PROJECT;
    SELECT INTO * FROM TASK;
    SELECT INTO * FROM PROJECT_SCHEDULE;
    SELECT INTO * FROM ASSIGNMENT;
    SELECT INTO * FROM WORK_LOG;
    SELECT INTO * FROM BILL;
END;