CREATE OR REPLACE PROCEDURE REGION_1_EXIST

IS 
reg1 number:=0;
counter_reg1 number:=0;
output varchar2(250):=0;
BEGIN
SELECT COUNT(CUSTOMER.REGION_ID) INTO reg1 FROM CUSTOMER WHERE CUSTOMER.REGION_ID = 'REGION_1';
IF (reg1>0) THEN dbms_output.put_line('Yes we have region 1');
END IF;
END;
/
EXECUTE REGION_1_EXIST(); 
