CREATE OR REPLACE PROCEDURE CURRENT_DAY_AND_DATE AS
BEGIN
  DBMS_OUTPUT.PUT_LINE( 'The current day and date is ' || TO_CHAR(SYSDATE, 'DL') );
END CURRENT_DAY_AND_DATE;
/

EXECUTE CURRENT_DAY_AND_DATE();